Fix filesystem doc
andrewdalpino/Rubix-engine pull request #330
Opened 2024-04-21 19:28 UTC by MocioF

2024-04-21 19:33 UTC, MocioF commented
have read the CLA Document and I hereby sign the CLA

2024-04-21 19:33 UTC, MocioF commented
recheck

2024-04-21 20:46 UTC, andrewdalpino requested changes
Good start!

2024-04-21 20:46 UTC, andrewdalpino commented on docs/persisters/filesystem.md
> +use Rubix\ML\Classifiers\KNearestNeighbors;
Looks like these next two imports are unused in the block of code below. If so, let's remove them.

2024-04-21 20:46 UTC, andrewdalpino commented on docs/persisters/filesystem.md
> +
Looks like an extra line break here, if so let's remove it.

2024-05-06 21:40 UTC, andrewdalpino approved these changes

2024-05-06 21:40 UTC, merged